name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      working-directory: ./monolith
      run: go build -v -o ./out/ ./...

    - name: Build client
      working-directory: ./monolith
      run: go build -v -o ./out/client ./client/client.go


    - name: Build proto client
      working-directory: ./proto
      run: go build -v -o ./out/client ./client/main.go 

      - name: Build proto server
      working-directory: ./proto
      run: go build -v -o ./out/server ./server/main.go 